# fly.toml app configuration file generated for m-tgbot2-billowing-wildflower-7513 on 2023-11-19T20:38:41+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "m-tgbot2-billowing-wildflower-7513"
primary_region = "waw"

[build]
  image = "superustam/memehack_tgbot:latest"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
