# fly.toml app configuration file generated for upload-module on 2023-12-07T19:43:31+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "upload-module"
primary_region = "waw"

[build]
  image = "superustam/memehack_ocr:latest"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
