# fly.toml app configuration file generated for m-tgbot-wild-feather-2103 on 2023-11-25T15:17:58+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "m-tgbot"
primary_region = "waw"

[build]
  image = "superustam/memehack_tgbot:latest"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 512
